### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by fangledon** [fangledon/SPH-Fluid-Simualtion#1]
- [ ] Add surface tension force to SPH simulation
- [ ] Provide different initial setups when user enter different numbers
- [ ] Switch to use new OpenGL pipeline
- [ ] Add Marching Cubes to render particles
